# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8448a8f9d96c4e14f99af2fc063e5f836fc6a9c0c4db98ab111ef864a5260f28fba151ceae940ac7384e78b2e57aad4c076eeb334919ffe1e6ca04dadce3fd9d

test:
  secret_key_base: 31ff8489f5ca409f99b2883aa4158edf80aef7a018f4ed36889f15a8c1223c2bb0f31ae72dd550964c3d2f4a3acf946cf421940fbb78fce677eaf62248a26872

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
